name: Cleanup Feed

on:
  schedule:
    - cron: "0 5 * * 5"
  workflow_dispatch:

concurrency:
  group: cleanup-feed
  cancel-in-progress: true

jobs:
  cleanup-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e .

      - name: Delete old posts, reposts, and likes
        run: python main.py
        env:
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DRY_RUN: ${{ vars.DRY_RUN }}
          DAYS_AGO: ${{ vars.DAYS_AGO }}
